/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.qlks.view.internalframe;

import com.qlks.custom.FunctionBase;
import com.qlks.dao.impl.ThongKeHieuSuatPhongDAO;
import com.qlks.models.ThongKePhong;
import java.util.List;
import java.util.ResourceBundle;
import javax.swing.table.DefaultTableModel;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.data.general.DefaultPieDataset;
import org.jfree.data.general.PieDataset;

/**
 *
 * @author hello
 */
public class BieuDoHieuSuatPhong extends javax.swing.JInternalFrame {

    private ThongKeHieuSuatPhongDAO thongKeHieuSuatPhongDAO;
    private List<ThongKePhong> lstThongKeHieuSuatPhong;
    private DefaultTableModel dtmThongKeHieuSuatPhong;
    private FunctionBase funcBase;
    ResourceBundle rb;

    public BieuDoHieuSuatPhong(ResourceBundle rb) {
        initComponents();
        this.rb = rb;
        thongKeHieuSuatPhongDAO = new ThongKeHieuSuatPhongDAO();
        funcBase = new FunctionBase();
        JFreeChart pieChart = createChart(createDataset());
        ChartPanel chartPanel = new ChartPanel(pieChart);
        jPanel1.add(chartPanel);
    }

    private static JFreeChart createChart(PieDataset dataset) {
        JFreeChart chart = ChartFactory.createPieChart(
                "CƠ CẤU DÂN SỐ THEO NHÓM TUỔI NĂM 2010", dataset, true, true, true);
        return chart;
    }

    private static PieDataset createDataset() {
        DefaultPieDataset dataset = new DefaultPieDataset();
        dataset.setValue("Nhóm 0 - 14", new Double(25.0));
        dataset.setValue("Nhóm 15 - 59", new Double(66.0));
        dataset.setValue("Nhóm trên 60", new Double(9.0));
        return dataset;
    }

//    public void loadData(LocalDate ngayInput1, LocalDate ngayInput2) {
//        LocalDate date1 = LocalDate.parse("2000-01-15");
//        LocalDate date2 = LocalDate.parse("2100-01-15");
//        if (ngayInput1 != null && ngayInput2 != null) {
//            lstThongKeHieuSuatPhong = thongKeHieuSuatPhongDAO.getAll(ngayInput1, ngayInput2);
//        } else if (ngayInput1 == null && ngayInput2 != null) {
//            lstThongKeHieuSuatPhong = thongKeHieuSuatPhongDAO.getAll(date1, ngayInput2);
//        } else if (ngayInput1 != null && ngayInput2 == null) {
//            lstThongKeHieuSuatPhong = thongKeHieuSuatPhongDAO.getAll(ngayInput1, date2);
//        } else {
//            lstThongKeHieuSuatPhong = thongKeHieuSuatPhongDAO.getAll(date1, date2);
//        }
//
//        Object[] columnNames = {"STT", "Mã phòng", "Hiệu suất thuê(%)", "Số ngày thuê", "Số lần thuê", "Tiền phòng", "Tiền dịch vụ", "Tiền giảm giá", "Tổng tiền"};
//        dtmThongKeHieuSuatPhong = new DefaultTableModel(new Object[0][0], columnNames);
//        int index = 1;
//        for (ThongKePhong adv : lstThongKeHieuSuatPhong) {
//            Object[] o = new Object[9];
//            o[0] = index;
//            o[1] = adv.getMaPhong();
//            o[2] = adv.getHieuSuatPhong();
//            o[3] = adv.getSoNgay();
//            o[4] = adv.getSoLanThue();
//            o[5] = (int) adv.getTienPhong();
//            o[6] = (int) adv.getTienDichVu();
//            o[7] = (int) adv.getGiamGia();
//            o[8] = (int) adv.getTongTien();
//            dtmThongKeHieuSuatPhong.addRow(o);
//            index++;
//        }
//        tblThongKeHieuSuatPhong.setModel(dtmThongKeHieuSuatPhong);
//    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpanelMain = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();

        setClosable(true);
        setIconifiable(true);
        setTitle("Thống kê hiệu suất phòng");

        javax.swing.GroupLayout jpanelMainLayout = new javax.swing.GroupLayout(jpanelMain);
        jpanelMain.setLayout(jpanelMainLayout);
        jpanelMainLayout.setHorizontalGroup(
            jpanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpanelMainLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jpanelMainLayout.setVerticalGroup(
            jpanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpanelMainLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpanelMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpanelMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jpanelMain;
    // End of variables declaration//GEN-END:variables

}
