/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.qlks.view.internalframe;

import com.qlks.dao.impl.NguoiDungDAO;
import com.qlks.models.NguoiDung;
import com.qlks.utils.MethodMain;
import java.awt.Color;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.util.Arrays;
import java.util.List;
import javax.swing.JLabel;
import javax.swing.JPasswordField;

/**
 *
 * @author hoangdung
 */
public class DoiMatKhauNguoiDung extends javax.swing.JInternalFrame {

    /**
     * Creates new form DoiMatKhauNguoiDung
     */
    List<NguoiDung> listNd;
    private NguoiDungDAO nddao = new NguoiDungDAO();

    public DoiMatKhauNguoiDung(List<NguoiDung> listNd) {
        initComponents();
        this.listNd = listNd;
        showPass(jlbshowOldPass, jpassOldPass);
        showPass(jlbShowNewPass, jpassNewPass);
        showPass(jlbShowRePass, jpassRePass);
    }

    private void showPass(JLabel jlb, JPasswordField jpass) {
        jlb.addMouseListener(new MouseListener() {
            @Override
            public void mouseClicked(MouseEvent me) {
            }

            @Override
            public void mousePressed(MouseEvent me) {
                jpass.setEchoChar((char) 0);
            }

            @Override
            public void mouseReleased(MouseEvent me) {
                jpass.setEchoChar('•');
            }

            @Override
            public void mouseEntered(MouseEvent me) {
                jpass.setBackground(Color.pink);
            }

            @Override
            public void mouseExited(MouseEvent me) {
                jpass.setBackground(Color.white);
            }
        });
    }

    private void clearInput() {
        jpassOldPass.setText(null);
        jpassNewPass.setText(null);
        jpassRePass.setText(null);
    }

    private void clearMsg() {
        jlbChangePassMgs.setText(null);
        jlbMsgOldPass.setText(null);
        jlbMsgNewPass.setText(null);
        jlbMsgRePass.setText(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jpassOldPass = new javax.swing.JPasswordField();
        jlbOldPass = new javax.swing.JLabel();
        jlbshowOldPass = new javax.swing.JLabel();
        jlbShowNewPass = new javax.swing.JLabel();
        jpassNewPass = new javax.swing.JPasswordField();
        jlbNewPass = new javax.swing.JLabel();
        jpassRePass = new javax.swing.JPasswordField();
        jlbRepass = new javax.swing.JLabel();
        jlbShowRePass = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jlbMsgOldPass = new javax.swing.JLabel();
        jlbMsgNewPass = new javax.swing.JLabel();
        jlbMsgRePass = new javax.swing.JLabel();
        jlbChangePassMgs = new javax.swing.JLabel();

        setClosable(true);

        jpassOldPass.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N
        jpassOldPass.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 15, 0, 15));
        jpassOldPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jpassOldPassActionPerformed(evt);
            }
        });

        jlbOldPass.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N
        jlbOldPass.setForeground(new java.awt.Color(0, 0, 0));
        jlbOldPass.setText("Mật khẩu cũ");

        jlbshowOldPass.setBackground(new java.awt.Color(140, 170, 90));
        jlbshowOldPass.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbshowOldPass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/qlks/icon/icon_passwordeye.png"))); // NOI18N
        jlbshowOldPass.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jlbshowOldPass.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jlbShowNewPass.setBackground(new java.awt.Color(140, 170, 90));
        jlbShowNewPass.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbShowNewPass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/qlks/icon/icon_passwordeye.png"))); // NOI18N
        jlbShowNewPass.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jlbShowNewPass.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jpassNewPass.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N
        jpassNewPass.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 15, 0, 15));
        jpassNewPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jpassNewPassActionPerformed(evt);
            }
        });

        jlbNewPass.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N
        jlbNewPass.setForeground(new java.awt.Color(0, 0, 0));
        jlbNewPass.setText("Mật khẩu mới");

        jpassRePass.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N
        jpassRePass.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 15, 0, 15));
        jpassRePass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jpassRePassActionPerformed(evt);
            }
        });

        jlbRepass.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N
        jlbRepass.setForeground(new java.awt.Color(0, 0, 0));
        jlbRepass.setText("Nhập lại mật khẩu");

        jlbShowRePass.setBackground(new java.awt.Color(140, 170, 90));
        jlbShowRePass.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbShowRePass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/qlks/icon/icon_passwordeye.png"))); // NOI18N
        jlbShowRePass.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jlbShowRePass.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jButton1.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N
        jButton1.setText("Đồng ý");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N
        jButton2.setText("Nhập lại");
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jlbMsgOldPass.setFont(new java.awt.Font("DejaVu Sans Condensed", 0, 12)); // NOI18N
        jlbMsgOldPass.setForeground(new java.awt.Color(248, 7, 7));

        jlbMsgNewPass.setFont(new java.awt.Font("DejaVu Sans Condensed", 0, 12)); // NOI18N
        jlbMsgNewPass.setForeground(new java.awt.Color(248, 7, 7));

        jlbMsgRePass.setFont(new java.awt.Font("DejaVu Sans Condensed", 0, 12)); // NOI18N
        jlbMsgRePass.setForeground(new java.awt.Color(248, 7, 7));
        jlbMsgRePass.setToolTipText("");

        jlbChangePassMgs.setFont(new java.awt.Font("DejaVu Sans", 1, 18)); // NOI18N
        jlbChangePassMgs.setForeground(new java.awt.Color(82, 134, 51));
        jlbChangePassMgs.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(70, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jlbOldPass, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(1, 1, 1)
                                .addComponent(jpassOldPass, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(jlbshowOldPass, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jlbNewPass, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(1, 1, 1)
                                .addComponent(jpassNewPass, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(jlbShowNewPass, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jlbRepass, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(1, 1, 1)
                                .addComponent(jpassRePass, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(jlbShowRePass, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jlbMsgOldPass, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jlbMsgNewPass, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlbMsgRePass, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(63, 63, 63))
            .addComponent(jlbChangePassMgs, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jlbChangePassMgs, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlbshowOldPass, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jpassOldPass, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jlbOldPass, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, 0)
                .addComponent(jlbMsgOldPass)
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlbShowNewPass, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jpassNewPass, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jlbNewPass, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, 0)
                .addComponent(jlbMsgNewPass)
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlbShowRePass, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jpassRePass, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jlbRepass, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, 0)
                .addComponent(jlbMsgRePass)
                .addGap(49, 49, 49)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(105, 105, 105))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jpassOldPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jpassOldPassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jpassOldPassActionPerformed

    private void jpassNewPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jpassNewPassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jpassNewPassActionPerformed

    private void jpassRePassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jpassRePassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jpassRePassActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        boolean check = true;
        clearMsg();
        String isNull = " ís Null";
        List<NguoiDung> listNguoiDung = nddao.getByMa(listNd.get(0).getMaNguoiDung());

        String oldPass = new String(jpassOldPass.getPassword());
        String newPass = new String(jpassNewPass.getPassword());

        if (jpassOldPass.getPassword().length == 0) {
            jlbMsgOldPass.setText(jlbOldPass.getText() + isNull);
            check = false;
        } else if (!oldPass.equals(listNguoiDung.get(0).getMatKhau())) {
            jlbMsgOldPass.setText(jlbOldPass.getText() + " Không chính xác");
            check = false;
        }

        if (jpassNewPass.getPassword().length == 0) {
            jlbMsgNewPass.setText(jlbNewPass.getText() + isNull);
            check = false;
        }

        if (jpassRePass.getPassword().length == 0) {
            jlbMsgRePass.setText(jlbRepass.getText() + isNull);
            check = false;
        } else if (!Arrays.equals(jpassNewPass.getPassword(), jpassRePass.getPassword())) {
            jlbMsgRePass.setText(jlbRepass.getText() + " Không chính xác");
            check = false;
        }

        if (check) {
            if (nddao.updatePassword(listNguoiDung.get(0).getMaNguoiDung(), newPass) > 0) {
                jlbChangePassMgs.setText("Đổi mật khẩu thành công");
            }

        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        clearInput();
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jlbChangePassMgs;
    private javax.swing.JLabel jlbMsgNewPass;
    private javax.swing.JLabel jlbMsgOldPass;
    private javax.swing.JLabel jlbMsgRePass;
    private javax.swing.JLabel jlbNewPass;
    private javax.swing.JLabel jlbOldPass;
    private javax.swing.JLabel jlbRepass;
    private javax.swing.JLabel jlbShowNewPass;
    private javax.swing.JLabel jlbShowRePass;
    private javax.swing.JLabel jlbshowOldPass;
    private javax.swing.JPasswordField jpassNewPass;
    private javax.swing.JPasswordField jpassOldPass;
    private javax.swing.JPasswordField jpassRePass;
    // End of variables declaration//GEN-END:variables
}
