/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.qlks.view.internalframe;

import com.qlks.view.internalframe.Item;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.lang.reflect.InvocationTargetException;
import java.lang.reflect.Method;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JComboBox;
import javax.swing.JList;
import javax.swing.plaf.basic.BasicComboBoxRenderer;

/**
 *
 * @author hoangdung
 */
public class NgonNgu extends javax.swing.JInternalFrame {

    /**
     * Creates new form NgonNgu
     */
    public NgonNgu() {
        initComponents();

        DefaultComboBoxModel model = new DefaultComboBoxModel<String>();
        model.addElement(new Item("phap",new ImageIcon("src/com/qlks/icon/icon_flag_fr.png"), "Phap"));
        model.addElement(new Item("anh",new ImageIcon("src/com/qlks/icon/icon_flag_uk.png"), "Anh"));
        model.addElement(new Item("vietnam",new ImageIcon("src/com/qlks/icon/icon_flag_vn.png"), "Viet Nam"));

        jcbLang.setModel(model);
        jcbLang.setRenderer(new ItemRenderer());

        jcbLang.addActionListener((ActionEvent e) -> {

            Item it = (Item) jcbLang.getSelectedItem();

            jlbLangFlag.setIcon(it.getIcon());

        });

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jcbLang = new javax.swing.JComboBox<>();
        jlbLangFlag = new javax.swing.JLabel();
        jpnLangOk = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setClosable(true);

        jcbLang.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N
        jcbLang.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jcbLang.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jlbLangFlag.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbLangFlag.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/qlks/icon/icon_flag_vn.png"))); // NOI18N

        jpnLangOk.setBackground(new java.awt.Color(160, 223, 104));
        jpnLangOk.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel1.setBackground(new java.awt.Color(116, 244, 144));
        jLabel1.setFont(new java.awt.Font("DejaVu Sans Condensed", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Dong y");

        javax.swing.GroupLayout jpnLangOkLayout = new javax.swing.GroupLayout(jpnLangOk);
        jpnLangOk.setLayout(jpnLangOkLayout);
        jpnLangOkLayout.setHorizontalGroup(
            jpnLangOkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
        );
        jpnLangOkLayout.setVerticalGroup(
            jpnLangOkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnLangOkLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jlbLangFlag, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jcbLang, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jpnLangOk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(85, 85, 85))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jlbLangFlag, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jcbLang))
                .addGap(18, 18, 18)
                .addComponent(jpnLangOk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 26, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox<String> jcbLang;
    private javax.swing.JLabel jlbLangFlag;
    private javax.swing.JPanel jpnLangOk;
    // End of variables declaration//GEN-END:variables
}

class Item {

    private String id;
    private Icon icon;
    private String text;

    public Item(String id, Icon icon, String text) {
        this.id = id;
        this.icon = icon;
        this.text = text;
    }

    public Icon getIcon() {
        return icon;
    }

    public String getText() {
        return text;
    }

    public String getId() {
        return id;
    }

}

class ItemRenderer extends BasicComboBoxRenderer {

    public Component getListCellRendererComponent(JList list, Object value,
            int index, boolean isSelected, boolean cellHasFocus) {
        super.getListCellRendererComponent(list, value, index, isSelected,
                cellHasFocus);

        Item item = (Item) value;

        if (index == -1) {
            setText(item.getText());
            setIcon(null);
        } else {
            setText(item.getText());
            setIcon(item.getIcon());
        }
        return this;
    }
}
