/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.qlks.view.internalframe;

import com.qlks.custom.FunctionBase;
import com.qlks.dao.impl.DonViDAO;
import com.qlks.models.DonVi;
import com.qlks.utils.MethodMain;
import java.util.List;
import java.util.Locale;
import java.util.ResourceBundle;
import javax.swing.JOptionPane;
import javax.swing.border.TitledBorder;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author MinhVuFC
 */
public class QuanLyDonVi extends javax.swing.JInternalFrame {

    private DonViDAO donviDAO;
    private List<DonVi> lstDonVi;
    private DefaultTableModel dtmDonVi;
    private FunctionBase funcBase;
    ResourceBundle rb;
    private Locale lc;

    /**
     * Creates new form QuanLyTaiSan
     */
    public QuanLyDonVi(Locale lc) {
        initComponents();
        this.lc = lc;
        this.rb = ResourceBundle.getBundle("com.qlks.i18n.resources.resources", this.lc);
        dtmDonVi = new DefaultTableModel();
        donviDAO = new DonViDAO();
        funcBase = new FunctionBase();
        loadData(null, null);
        resetText();
        if (!MethodMain.checkQuyen("QlDichVu")) {
            jpnDonVi.setVisible(false);
        }
    }

    public void loadData(String maSeaechInput, String noidungSearchInput) {
        Object[] columnNames = {"STT", "Mã đơn vị", "Tên đơn vị", ""};

        if (maSeaechInput == null || noidungSearchInput == null) {
            maSeaechInput = "";
            noidungSearchInput = "";
        }
        lstDonVi = donviDAO.search(maSeaechInput, noidungSearchInput);

        dtmDonVi = new DefaultTableModel(new Object[0][0], columnNames);
        int index = 1;
        for (DonVi adv : lstDonVi) {
            Object[] o = new Object[4];
            o[0] = index;
            o[1] = adv.getMaDonVi();
            o[2] = adv.getTenDonVi();
            dtmDonVi.addRow(o);
            index++;
        }
        tblDonVi.setModel(dtmDonVi);
        funcBase.addCheckBox(3, tblDonVi);

        // Cài đặt sự kiện khi click từng dòng trong bảng
        if (lstDonVi.size() > 0) {
            tblDonVi.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
                @Override
                public void valueChanged(ListSelectionEvent e) {
                    int currentRow = tblDonVi.getSelectedRow();
                    if (currentRow < 0) {
                        currentRow = 0;
                    }

                    // Chèn dữ liệu lên form
                    if (currentRow >= 0) {
                        txtMaDonVi.setText(tblDonVi.getValueAt(currentRow, 1).toString());
                        txtTenDonVi.setText(tblDonVi.getValueAt(currentRow, 2).toString());
                    }
                }
            });
        }
        translate(lc);
    }

    public void resetText() {
        txtMaDonVi.setText("");
        txtTenDonVi.setText("");
        txtErrorMaDV.setText("");
        txtErrorTenDV.setText("");
    }

    private void makeText(ResourceBundle rb) {
        btnCapNhat.setText(rb.getString("BtnCapNhat"));
        btnLamMoi.setText(rb.getString("BtnLamMoi"));
        btnThemMoi.setText(rb.getString("BtnThemMoi"));
        btnTimKiem.setText(rb.getString("BtnTimKiem"));
        btnXoa.setText(rb.getString("BtnXoa"));
        setTitle(rb.getString("JIFQLDonVi"));
        ((TitledBorder) jpnDonVi.getBorder()).setTitle(rb.getString("JIFQLDonViBorder"));
        jlbMaDonVi.setText(rb.getString("JIFQLDonViMa"));
        jlbMaDonVi1.setText(rb.getString("JIFQLDonViMa"));
        jlbTenDonVi.setText(rb.getString("JIFQLDonViTen"));
        jlbTenDonVi1.setText(rb.getString("JIFQLDonViTen"));
    }

    private void makeTableHeader(ResourceBundle rb) {
        tblDonVi.getColumnModel().getColumn(0).setHeaderValue("STT");
        tblDonVi.getColumnModel().getColumn(1).setHeaderValue(rb.getString("JIFQLDonViMa"));
        tblDonVi.getColumnModel().getColumn(2).setHeaderValue(rb.getString("JIFQLDonViTen"));
        tblDonVi.getColumnModel().getColumn(3).setHeaderValue("");
    }

    public void translate(Locale lc) {
        this.rb = ResourceBundle.getBundle("com.qlks.i18n.resources.resources", lc);
        this.lc = lc;
        makeText(this.rb);
        makeTableHeader(this.rb);
        revalidate();
        repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpnDonVi = new javax.swing.JPanel();
        jlbMaDonVi1 = new javax.swing.JLabel();
        jlbTenDonVi1 = new javax.swing.JLabel();
        txtTenDonVi = new javax.swing.JTextField();
        btnThemMoi = new javax.swing.JButton();
        btnCapNhat = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        lblResult = new javax.swing.JLabel();
        btnLamMoi = new javax.swing.JButton();
        txtMaDonVi = new javax.swing.JTextField();
        txtErrorMaDV = new javax.swing.JLabel();
        txtErrorTenDV = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDonVi = new javax.swing.JTable();
        btnTimKiem = new javax.swing.JButton();
        txtSearchMaDV = new javax.swing.JTextField();
        txtSearchTenDV = new javax.swing.JTextField();
        jlbMaDonVi = new javax.swing.JLabel();
        jlbTenDonVi = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setTitle("Quản lý đơn vị");

        jpnDonVi.setBorder(javax.swing.BorderFactory.createTitledBorder("Đơn vị"));

        jlbMaDonVi1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jlbMaDonVi1.setText("Mã đơn vị:");

        jlbTenDonVi1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jlbTenDonVi1.setText("Tên đơn vị:");

        txtTenDonVi.setColumns(5);
        txtTenDonVi.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        btnThemMoi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/qlks/icon/icon_add.png"))); // NOI18N
        btnThemMoi.setText("Thêm mới");
        btnThemMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemMoiActionPerformed(evt);
            }
        });

        btnCapNhat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/qlks/icon/icon_edit.png"))); // NOI18N
        btnCapNhat.setText("Cập nhật");
        btnCapNhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCapNhatActionPerformed(evt);
            }
        });

        btnXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/qlks/icon/icon_delete.png"))); // NOI18N
        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        lblResult.setForeground(new java.awt.Color(248, 13, 33));

        btnLamMoi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/qlks/icon/icon_refresh.png"))); // NOI18N
        btnLamMoi.setText("Làm mới");
        btnLamMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLamMoiActionPerformed(evt);
            }
        });

        txtMaDonVi.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        txtErrorMaDV.setForeground(new java.awt.Color(255, 0, 0));
        txtErrorMaDV.setText("...");

        txtErrorTenDV.setForeground(new java.awt.Color(255, 0, 0));
        txtErrorTenDV.setText("...");

        javax.swing.GroupLayout jpnDonViLayout = new javax.swing.GroupLayout(jpnDonVi);
        jpnDonVi.setLayout(jpnDonViLayout);
        jpnDonViLayout.setHorizontalGroup(
            jpnDonViLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnDonViLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpnDonViLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpnDonViLayout.createSequentialGroup()
                        .addGap(161, 161, 161)
                        .addComponent(lblResult, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jpnDonViLayout.createSequentialGroup()
                        .addComponent(btnLamMoi)
                        .addGap(2, 2, 2)
                        .addComponent(btnThemMoi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCapNhat)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnXoa)
                        .addGap(0, 8, Short.MAX_VALUE))
                    .addGroup(jpnDonViLayout.createSequentialGroup()
                        .addGroup(jpnDonViLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlbMaDonVi1)
                            .addComponent(jlbTenDonVi1))
                        .addGap(18, 18, 18)
                        .addGroup(jpnDonViLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTenDonVi)
                            .addComponent(txtMaDonVi)
                            .addComponent(txtErrorMaDV, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtErrorTenDV, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        jpnDonViLayout.setVerticalGroup(
            jpnDonViLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnDonViLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpnDonViLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbMaDonVi1)
                    .addComponent(txtMaDonVi, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtErrorMaDV)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpnDonViLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTenDonVi, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlbTenDonVi1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtErrorTenDV)
                .addGap(11, 11, 11)
                .addComponent(lblResult)
                .addGap(18, 18, 18)
                .addGroup(jpnDonViLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLamMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnThemMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCapNhat, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(328, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        tblDonVi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblDonVi);

        btnTimKiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/qlks/icon/icon_search.png"))); // NOI18N
        btnTimKiem.setText("Tìm kiếm");
        btnTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemActionPerformed(evt);
            }
        });

        txtSearchMaDV.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        txtSearchTenDV.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jlbMaDonVi.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jlbMaDonVi.setText("Mã đơn vị:");

        jlbTenDonVi.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jlbTenDonVi.setText("Tên đơn vị:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 549, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 71, 71))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtSearchMaDV, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlbMaDonVi))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jlbTenDonVi)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txtSearchTenDV, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnTimKiem)
                        .addGap(130, 130, 130))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbMaDonVi)
                    .addComponent(jlbTenDonVi))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSearchTenDV, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSearchMaDV, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 577, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jpnDonVi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpnDonVi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnThemMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemMoiActionPerformed
        String maDVi = txtMaDonVi.getText().trim();
        String tenDVi = txtTenDonVi.getText().trim();
        Boolean ckeck = true;
        List<DonVi> lstCheckID = donviDAO.getByMa(maDVi);
        if (maDVi.length() <= 0) {
            txtErrorMaDV.setText("Mã đơn vị không được để trống !");
            ckeck = false;
        } else {
            txtErrorMaDV.setText("");
        }
        if (maDVi.length() > 3) {
            txtErrorMaDV.setText("Mã đơn vị tối đa là 3 ký tự !");
            ckeck = false;
        }
        if (lstCheckID.size() > 0) {
            txtErrorMaDV.setText("Mã đơn vị đã tồn tại !");
            ckeck = false;
        }
        if (tenDVi.length() <= 0) {
            txtErrorTenDV.setText("Tên đơn vị không được để trống !");
            ckeck = false;
        } else {
            txtErrorTenDV.setText("");
        }
        if (tenDVi.length() > 50) {
            txtErrorTenDV.setText("Tên đơn vị tối đa là 50 ký tự !");
            ckeck = false;
        }
        if (ckeck == true) {
            int row = donviDAO.add(new DonVi(maDVi, tenDVi));
            if (row > 0) {
                JOptionPane.showMessageDialog(rootPane, "Thêm thành công", null, JOptionPane.INFORMATION_MESSAGE);
                loadData(null, null);
                resetText();
            } else {
                JOptionPane.showMessageDialog(rootPane, "Thêm thất bại", null, JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnThemMoiActionPerformed

    private void btnCapNhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCapNhatActionPerformed
        int currentRow = tblDonVi.getSelectedRow();

        if (currentRow >= 0) {
            String maDVi = txtMaDonVi.getText().trim();
            String tenDVi = txtTenDonVi.getText().trim();
            Boolean ckeck = true;

            List<DonVi> lstCheckID = donviDAO.getByMa(maDVi);

            if (maDVi.length() <= 0) {
                txtErrorMaDV.setText("Mã đơn vị không được để trống !");
                ckeck = false;
            } else {
                txtErrorMaDV.setText("");
            }
            if (maDVi.length() > 3) {
                txtErrorMaDV.setText("Mã đơn vị tối đa là 3 ký tự !");
                ckeck = false;
            }
            if (tenDVi.length() <= 0) {
                txtErrorTenDV.setText("Tên đơn vị không được để trống !");
                ckeck = false;
            } else {
                txtErrorTenDV.setText("");
            }
            if (tenDVi.length() > 50) {
                txtErrorTenDV.setText("Tên đơn vị tối đa là 50 ký tự !");
                ckeck = false;
            }
            if (ckeck == true) {
                if (lstCheckID.size() < 0) {
                    txtErrorMaDV.setText("Mã đơn vị không tồn tại !");
                } else {
                    int row = donviDAO.update(new DonVi(maDVi, tenDVi));
                    if (row > 0) {
                        JOptionPane.showMessageDialog(rootPane, "Cập nhật thành công", null, JOptionPane.INFORMATION_MESSAGE);
                        loadData(null, null);
                        resetText();
                    } else {
                        JOptionPane.showMessageDialog(rootPane, "Cập nhật thất bại", null, JOptionPane.ERROR_MESSAGE);
                    }
                }
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "Vui lòng chọn hàng để cập nhật", "Thông báo", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnCapNhatActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        String succesDeltete = "";
        String errDeltete = "";
        
        Boolean check = false;
        int thongbao = JOptionPane.showConfirmDialog(this, "Bạn có chắc chắn không ?", "Thông báo", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (thongbao == JOptionPane.YES_OPTION) {

            for (int i = 0; i < tblDonVi.getRowCount(); i++) {
                if (funcBase.IsSelected(i, 3, tblDonVi)) {
                    check = true;
                    int rowSucces = donviDAO.delete(tblDonVi.getValueAt(i, 1).toString());
                    tblDonVi.clearSelection();
                    if (rowSucces > 0) {
                        succesDeltete += "\t" + tblDonVi.getValueAt(i, 2).toString() + "\n";
                    } else {
                        errDeltete += "\t" + tblDonVi.getValueAt(i, 2).toString() + "\n";
                    }
                }
            }
            loadData(null, null);
            resetText();
            if (check == true) {
                String mess = "";
                if (succesDeltete.length() > 0) {
                    mess += "Bạn đã xóa thành công: \n" + succesDeltete;
                }
                if (errDeltete.length() > 0) {
                    mess += "Không thể xóa: \n" + errDeltete;
                }
                JOptionPane.showMessageDialog(rootPane, mess, "Thông báo", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(rootPane, "Vui lòng chọn hàng để xóa", "Thông báo", JOptionPane.WARNING_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnLamMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLamMoiActionPerformed
        txtSearchMaDV.setText("");
        txtSearchTenDV.setText("");
        loadData(null, null);
        resetText();
    }//GEN-LAST:event_btnLamMoiActionPerformed

    private void btnTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemActionPerformed
        tblDonVi.clearSelection();
        String maDViSearch = txtSearchMaDV.getText();
        String tenDViSearch = txtSearchTenDV.getText();
        if (maDViSearch == null) {
            maDViSearch = "";
        } else if (tenDViSearch == null) {
            tenDViSearch = "";
        }
        loadData(maDViSearch, tenDViSearch);
        resetText();
    }//GEN-LAST:event_btnTimKiemActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCapNhat;
    private javax.swing.JButton btnLamMoi;
    private javax.swing.JButton btnThemMoi;
    private javax.swing.JButton btnTimKiem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jlbMaDonVi;
    private javax.swing.JLabel jlbMaDonVi1;
    private javax.swing.JLabel jlbTenDonVi;
    private javax.swing.JLabel jlbTenDonVi1;
    private javax.swing.JPanel jpnDonVi;
    private javax.swing.JLabel lblResult;
    private javax.swing.JTable tblDonVi;
    private javax.swing.JLabel txtErrorMaDV;
    private javax.swing.JLabel txtErrorTenDV;
    private javax.swing.JTextField txtMaDonVi;
    private javax.swing.JTextField txtSearchMaDV;
    private javax.swing.JTextField txtSearchTenDV;
    private javax.swing.JTextField txtTenDonVi;
    // End of variables declaration//GEN-END:variables
}
