/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.qlks.view.internalframe.action;

import com.qlks.dao.impl.DichVuDAO;
import com.qlks.dao.impl.DonViDAO;
import com.qlks.dao.impl.LoaiDichVuDAO;
import com.qlks.models.DichVu;
import com.qlks.models.DonVi;
import com.qlks.models.LoaiDichVu;
import java.util.List;
import java.util.ResourceBundle;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author hello
 */
public class AddDichVu extends javax.swing.JInternalFrame {

    private DichVuDAO dichVuDAO;
    private LoaiDichVuDAO loaiDichVuDAO;
    private List<LoaiDichVu> lstLoaiDichVu;
    private DefaultComboBoxModel modelLoaiDichVu;
    private DonViDAO donViDAO;
    private List<DonVi> lstDonVi;
    private DefaultComboBoxModel modelDonVi;

    CallBackAdd cb;
    private ResourceBundle rb;
    

    public interface CallBackAdd {

        void doAdd();
    }

    /**
     * Creates new form AddKhachHang
     */
    public AddDichVu(CallBackAdd _cb, ResourceBundle rb) {
        initComponents();
        dichVuDAO = new DichVuDAO();

        modelLoaiDichVu = new DefaultComboBoxModel();
        loaiDichVuDAO = new LoaiDichVuDAO();
        lstLoaiDichVu = loaiDichVuDAO.getAll();

        modelDonVi = new DefaultComboBoxModel();
        donViDAO = new DonViDAO();
        lstDonVi = donViDAO.getAll();

        resetText();
        this.cb = _cb;
        initDataLoaiDichVu();
        initDataDonVi();
        this.rb = rb;
        translate(this.rb);
    }

    public void initDataLoaiDichVu() {
        for (LoaiDichVu adv : lstLoaiDichVu) {
            modelLoaiDichVu.addElement(adv);
        }
        jcbMaLoaiDVu.setModel(modelLoaiDichVu);
    }

    public void initDataDonVi() {
        for (DonVi adv : lstDonVi) {
            modelDonVi.addElement(adv);
        }
        jComboBoxMaDVi.setModel(modelDonVi);
    }

    public void resetText() {
        txtErrorMaMaDVu.setText("");
        txtMaDVu.setText("");
        txtDonGia.setText("");
        txtErrorDonGia.setText("");
    }

    public void translate(ResourceBundle rb) {
        this.rb = rb;
        setTitle(this.rb.getString("AddDichVu"));
        jlbTitle.setText(this.rb.getString("AddDichVu"));
        jlbMaDv.setText(this.rb.getString("JIFQLDichVuMa"));
        jlbTenLoaiDv.setText(this.rb.getString("JIFQLDichVu"));
        jlbDonVi.setText(this.rb.getString("DonVi"));
        jlbGiaTien.setText(this.rb.getString("JIFQuanLyPhongGia"));

        btnLamMoi.setText(this.rb.getString("BtnLamMoi"));
        btnHuyBo.setText(this.rb.getString("BtnHuy"));
        btnThemMoi.setText(this.rb.getString("BtnThemMoi"));

        revalidate();
        repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jlbTitle = new javax.swing.JLabel();
        jlbMaDv = new javax.swing.JLabel();
        txtMaDVu = new javax.swing.JTextField();
        jlbTenLoaiDv = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jlbGiaTien = new javax.swing.JLabel();
        btnHuyBo = new javax.swing.JButton();
        btnThemMoi = new javax.swing.JButton();
        btnLamMoi = new javax.swing.JButton();
        txtErrorMaMaDVu = new javax.swing.JLabel();
        jcbMaLoaiDVu = new javax.swing.JComboBox<>();
        jComboBoxMaDVi = new javax.swing.JComboBox<>();
        jlbDonVi = new javax.swing.JLabel();
        txtDonGia = new javax.swing.JTextField();
        txtErrorDonGia = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);

        jlbTitle.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlbTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbTitle.setText("THÊM MỚI DỊCH VỤ");

        jlbMaDv.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jlbMaDv.setText("Mã dịch vụ:");

        jlbTenLoaiDv.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jlbTenLoaiDv.setText("Tên loại DV:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jlbGiaTien.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jlbGiaTien.setText("Giá tiền:");

        btnHuyBo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnHuyBo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/qlks/icon/icon_close.png"))); // NOI18N
        btnHuyBo.setText("Hủy bỏ");
        btnHuyBo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHuyBoActionPerformed(evt);
            }
        });

        btnThemMoi.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnThemMoi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/qlks/icon/icon_add.png"))); // NOI18N
        btnThemMoi.setText("Thêm mới");
        btnThemMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemMoiActionPerformed(evt);
            }
        });

        btnLamMoi.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnLamMoi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/qlks/icon/icon_refresh.png"))); // NOI18N
        btnLamMoi.setText("Làm mới");
        btnLamMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLamMoiActionPerformed(evt);
            }
        });

        txtErrorMaMaDVu.setForeground(new java.awt.Color(255, 51, 51));
        txtErrorMaMaDVu.setText("...");

        jlbDonVi.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jlbDonVi.setText("Đơn vị:");

        txtDonGia.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        txtErrorDonGia.setForeground(new java.awt.Color(255, 51, 51));
        txtErrorDonGia.setText("...");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(241, Short.MAX_VALUE)
                .addComponent(jlbTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(232, 232, 232))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlbMaDv)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jlbTenLoaiDv, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jlbGiaTien, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(btnLamMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jlbDonVi)
                                .addGap(26, 26, 26)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnHuyBo, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(25, 25, 25)
                                .addComponent(btnThemMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jComboBoxMaDVi, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(65, 65, 65))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtErrorMaMaDVu, javax.swing.GroupLayout.DEFAULT_SIZE, 353, Short.MAX_VALUE)
                            .addComponent(txtMaDVu))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtDonGia)
                            .addComponent(jcbMaLoaiDVu, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtErrorDonGia, javax.swing.GroupLayout.DEFAULT_SIZE, 357, Short.MAX_VALUE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jlbTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbMaDv)
                    .addComponent(txtMaDVu, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addComponent(txtErrorMaMaDVu)
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbTenLoaiDv)
                    .addComponent(jcbMaLoaiDVu, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxMaDVi, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlbDonVi))
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbGiaTien)
                    .addComponent(txtDonGia, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtErrorDonGia)
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLamMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHuyBo, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnThemMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLamMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLamMoiActionPerformed
        resetText();
    }//GEN-LAST:event_btnLamMoiActionPerformed

    private void btnHuyBoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHuyBoActionPerformed
        resetText();
        dispose();
    }//GEN-LAST:event_btnHuyBoActionPerformed

    private void btnThemMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemMoiActionPerformed
        Boolean check = true;
        String maDV = txtMaDVu.getText();

        LoaiDichVu lp = (LoaiDichVu) modelLoaiDichVu.getSelectedItem();
        String ma_LoaiDichVu = lp.getMaLoaiDichVu();

        DonVi dv = (DonVi) modelDonVi.getSelectedItem();
        String ma_DonVi = dv.getMaDonVi();

        String gia = txtDonGia.getText();

        if (maDV.length() <= 0) {
            txtErrorMaMaDVu.setText("Mã không được để trống");
            check = false;
        } else if (maDV.length() > 5) {
            txtErrorMaMaDVu.setText("Mã có tối đa là 5 ký tự");
            check = false;
        } else {
            txtErrorMaMaDVu.setText("");
        }

        try {
            List<DichVu> lstCheckID = dichVuDAO.getDichVuByMa(maDV);
            if (lstCheckID.size() > 0) {
                txtErrorMaMaDVu.setText("Mã dịch vụ đã tồn tại !");
                check = false;
            }
        } catch (Exception e) {
            txtErrorMaMaDVu.setText("Mã dịch vụ đã tồn tại !");
        }
        Float giaInput = null;
        if (gia.length() <= 0) {
            txtErrorDonGia.setText("Giá không được để trống");
            check = false;
        } else {
            txtErrorDonGia.setText("");
            try {
                giaInput = Float.parseFloat(gia);
                if (giaInput < 0) {
                    txtErrorDonGia.setText("Giá phải lớn hơn hoặc bằng 0");
                    check = false;
                }
            } catch (Exception e) {
                txtErrorDonGia.setText("Giá phải lớn hơn hoặc bằng 0");
                check = false;
            }
        }
        if (check == true) {
            int row = dichVuDAO.add(new DichVu(maDV, ma_LoaiDichVu, ma_DonVi, giaInput));
            if (row > 0) {
                JOptionPane.showMessageDialog(rootPane, "Thêm thành công", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                resetText();
                cb.doAdd();
                dispose();
            } else {
                JOptionPane.showMessageDialog(rootPane, "Thêm thất bại", "Thông báo", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnThemMoiActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHuyBo;
    private javax.swing.JButton btnLamMoi;
    private javax.swing.JButton btnThemMoi;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<DonVi> jComboBoxMaDVi;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox<LoaiDichVu> jcbMaLoaiDVu;
    private javax.swing.JLabel jlbDonVi;
    private javax.swing.JLabel jlbGiaTien;
    private javax.swing.JLabel jlbMaDv;
    private javax.swing.JLabel jlbTenLoaiDv;
    private javax.swing.JLabel jlbTitle;
    private javax.swing.JTextField txtDonGia;
    private javax.swing.JLabel txtErrorDonGia;
    private javax.swing.JLabel txtErrorMaMaDVu;
    private javax.swing.JTextField txtMaDVu;
    // End of variables declaration//GEN-END:variables
}
