/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.qlks.view.internalframe.action;

import com.qlks.dao.impl.KhachHangDAO;
import com.qlks.models.KhachHang;
import java.util.List;
import java.util.ResourceBundle;
import javax.swing.JOptionPane;

/**
 *
 * @author hello
 */
public class AddKhachHang extends javax.swing.JInternalFrame {

    private KhachHangDAO khachHangDAO;

    CallBackAdd cb;
    private ResourceBundle rb;

    public interface CallBackAdd {

        void doAddKH();
    }

    /**
     * Creates new form AddKhachHang
     */
    public AddKhachHang(CallBackAdd _cb, ResourceBundle rb) {
        initComponents();
        resetText();
        khachHangDAO = new KhachHangDAO();
        this.cb = _cb;
        this.rb = rb;
        translate(this.rb);
    }

    public void resetText() {
        txtErrorCMND.setText("");
        txtErrorDiaChi.setText("");
        txtErrorDienThoai.setText("");
        txtErrorMaKH.setText("");
        txtErrorQuocTich.setText("");
        txtErrorTenKH.setText("");

        txtDiaChi.setText("");
        txtMaKH.setText("");
        txtQuocTich.setText("");
        txtTenKH.setText("");
        txtDienThoai.setText("");
        txtCMND.setText("");
    }

    public void translate(ResourceBundle rb) {
        this.rb = rb;
        setTitle(this.rb.getString("AddKhachHang"));
        jlbTitle.setText(this.rb.getString("AddKhachHang"));
        jlbMaKh.setText(this.rb.getString("JIFQLKhachHangMa"));
        jlbTenKh.setText(this.rb.getString("JIFQLKhachHangTen"));
        jlbCMND.setText(this.rb.getString("JIFQLKhachHangCMND"));
        jlbDiaChi.setText(this.rb.getString("JIFQLKhachHangDiaChi"));
        jlbSDT.setText(this.rb.getString("JIFQLKhachHangSDT"));
        jlbQuocTich.setText(this.rb.getString("JIFQLKhachHangQuocTich"));
        jlbGioiTinh.setText(this.rb.getString("JIFQLKhachHangGioiTinh"));
        jRadioNam.setText(this.rb.getString("AddNdNam"));
        jRadioNu.setText(this.rb.getString("AddNdNu"));

        btnLamMoi.setText(this.rb.getString("BtnLamMoi"));
        btnHuyBo.setText(this.rb.getString("BtnHuy"));
        btnThemMoi.setText(this.rb.getString("BtnThemMoi"));

        revalidate();
        repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jlbTitle = new javax.swing.JLabel();
        jlbMaKh = new javax.swing.JLabel();
        txtMaKH = new javax.swing.JTextField();
        jlbTenKh = new javax.swing.JLabel();
        txtTenKH = new javax.swing.JTextField();
        jlbCMND = new javax.swing.JLabel();
        jlbDiaChi = new javax.swing.JLabel();
        txtDiaChi = new javax.swing.JTextField();
        txtQuocTich = new javax.swing.JTextField();
        jlbSDT = new javax.swing.JLabel();
        jlbGioiTinh = new javax.swing.JLabel();
        jlbQuocTich = new javax.swing.JLabel();
        jRadioNam = new javax.swing.JRadioButton();
        jRadioNu = new javax.swing.JRadioButton();
        btnHuyBo = new javax.swing.JButton();
        btnThemMoi = new javax.swing.JButton();
        btnLamMoi = new javax.swing.JButton();
        txtErrorMaKH = new javax.swing.JLabel();
        txtErrorTenKH = new javax.swing.JLabel();
        txtErrorCMND = new javax.swing.JLabel();
        txtErrorDiaChi = new javax.swing.JLabel();
        txtErrorDienThoai = new javax.swing.JLabel();
        txtErrorQuocTich = new javax.swing.JLabel();
        txtCMND = new javax.swing.JTextField();
        txtDienThoai = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);

        jlbTitle.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlbTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbTitle.setText("THÊM MỚI KHÁCH HÀNG");

        jlbMaKh.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jlbMaKh.setText("Mã khách hàng:");

        jlbTenKh.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jlbTenKh.setText("Tên khách hàng:");

        txtTenKH.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jlbCMND.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jlbCMND.setText("CMND:");

        jlbDiaChi.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jlbDiaChi.setText("Địa chỉ:");

        txtDiaChi.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        txtQuocTich.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jlbSDT.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jlbSDT.setText("Điện thoại:");

        jlbGioiTinh.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jlbGioiTinh.setText("Giới tính:");

        jlbQuocTich.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jlbQuocTich.setText("Quốc tịch:");

        buttonGroup1.add(jRadioNam);
        jRadioNam.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jRadioNam.setSelected(true);
        jRadioNam.setText("Nam");

        buttonGroup1.add(jRadioNu);
        jRadioNu.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jRadioNu.setText("Nữ");

        btnHuyBo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnHuyBo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/qlks/icon/icon_close.png"))); // NOI18N
        btnHuyBo.setText("Hủy bỏ");
        btnHuyBo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHuyBoActionPerformed(evt);
            }
        });

        btnThemMoi.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnThemMoi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/qlks/icon/icon_add.png"))); // NOI18N
        btnThemMoi.setText("Thêm mới");
        btnThemMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemMoiActionPerformed(evt);
            }
        });

        btnLamMoi.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnLamMoi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/qlks/icon/icon_refresh.png"))); // NOI18N
        btnLamMoi.setText("Làm mới");
        btnLamMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLamMoiActionPerformed(evt);
            }
        });

        txtErrorMaKH.setForeground(new java.awt.Color(255, 51, 51));
        txtErrorMaKH.setText("...");

        txtErrorTenKH.setForeground(new java.awt.Color(255, 0, 0));
        txtErrorTenKH.setText("...");

        txtErrorCMND.setForeground(new java.awt.Color(255, 0, 0));
        txtErrorCMND.setText("...");

        txtErrorDiaChi.setForeground(new java.awt.Color(255, 51, 51));
        txtErrorDiaChi.setText("...");

        txtErrorDienThoai.setForeground(new java.awt.Color(255, 0, 0));
        txtErrorDienThoai.setText("...");

        txtErrorQuocTich.setForeground(new java.awt.Color(255, 0, 0));
        txtErrorQuocTich.setText("...");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlbMaKh)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jlbSDT, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jlbCMND, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jlbGioiTinh, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 257, Short.MAX_VALUE)
                        .addComponent(btnLamMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnHuyBo, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25)
                        .addComponent(btnThemMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jRadioNam)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioNu))
                            .addComponent(txtMaKH, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtErrorMaKH, javax.swing.GroupLayout.DEFAULT_SIZE, 211, Short.MAX_VALUE)
                            .addComponent(txtErrorCMND, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtErrorDienThoai, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtCMND)
                            .addComponent(txtDienThoai))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlbDiaChi)
                            .addComponent(jlbTenKh)
                            .addComponent(jlbQuocTich, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtQuocTich)
                            .addComponent(txtDiaChi, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtTenKH, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtErrorTenKH, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 313, Short.MAX_VALUE)
                            .addComponent(txtErrorDiaChi, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtErrorQuocTich, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(67, 67, 67))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(233, 233, 233)
                .addComponent(jlbTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jlbTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbMaKh)
                    .addComponent(txtMaKH, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlbTenKh)
                    .addComponent(txtTenKH, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtErrorMaKH)
                    .addComponent(txtErrorTenKH))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlbCMND)
                            .addComponent(jlbDiaChi)
                            .addComponent(txtDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(txtCMND)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtErrorCMND)
                    .addComponent(txtErrorDiaChi))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbSDT)
                    .addComponent(jlbQuocTich)
                    .addComponent(txtQuocTich, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDienThoai, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtErrorDienThoai)
                    .addComponent(txtErrorQuocTich))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbGioiTinh)
                    .addComponent(jRadioNam)
                    .addComponent(jRadioNu))
                .addGap(60, 60, 60)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLamMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHuyBo, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnThemMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLamMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLamMoiActionPerformed
        resetText();
    }//GEN-LAST:event_btnLamMoiActionPerformed

    private void btnHuyBoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHuyBoActionPerformed
        resetText();
        dispose();
    }//GEN-LAST:event_btnHuyBoActionPerformed

    private void btnThemMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemMoiActionPerformed
        Boolean check = true;
        String maKH = txtMaKH.getText();
        String tenKH = txtTenKH.getText();
        String diaChi = txtDiaChi.getText();
        String quocTich = txtQuocTich.getText();
        String CMND = txtCMND.getText();
        String dienThoai = txtDienThoai.getText();
        Boolean gioiTinh = true;
        if (jRadioNu.isSelected()) {
            gioiTinh = false;
        }

        if (maKH.length() <= 0) {
            txtErrorMaKH.setText("Mã không được để trống");
            check = false;
        } else if (maKH.length() > 3) {
            txtErrorMaKH.setText("Mã có tối đa là 3 ký tự");
            check = false;
        } else {
            txtErrorMaKH.setText("");
        }

        List<KhachHang> lstCheckID = khachHangDAO.getByMa(maKH);
        if (lstCheckID.size() > 0) {
            txtErrorMaKH.setText("Mã khách hàng đã tồn tại !");
            check = false;
        }

        if (tenKH.length() <= 0) {
            txtErrorTenKH.setText("Tên không được để trống");
            check = false;
        } else if (tenKH.length() > 50) {
            txtErrorTenKH.setText("Tên có tối đa là 50 ký tự");
            check = false;
        } else {
            txtErrorTenKH.setText("");
        }

        if (CMND.length() <= 0) {
            txtErrorCMND.setText("CMND không được để trống");
            check = false;
        } else if (CMND.length() > 15) {
            txtErrorCMND.setText("CMND có tối đa là 15 ký tự");
            check = false;
        } else {
            txtErrorCMND.setText("");
        }

        if (diaChi.length() <= 0) {
            txtErrorDiaChi.setText("Địa chỉ không được để trống");
            check = false;
        } else if (diaChi.length() > 50) {
            txtErrorDiaChi.setText("Địa chỉ có tối đa là 50 ký tự");
            check = false;
        } else {
            txtErrorDiaChi.setText("");
        }

        if (dienThoai.length() <= 0) {
            txtErrorDienThoai.setText("Điện thoại không được để trống");
            check = false;
        } else if (dienThoai.length() > 15) {
            txtErrorDienThoai.setText("Điện thoại có tối đa là 15 số");
            check = false;
        } else {
            txtErrorDienThoai.setText("");
        }

        if (quocTich.length() <= 0) {
            txtErrorQuocTich.setText("Quốc tịch không được để trống");
            check = false;
        } else if (quocTich.length() > 50) {
            txtErrorQuocTich.setText("Quốc tịch có tối đa là 50 ký tự");
            check = false;
        } else {
            txtErrorQuocTich.setText("");
        }
        if (check == true) {

            txtErrorDienThoai.setText("");
            int row = khachHangDAO.add(new KhachHang(maKH, tenKH, CMND, diaChi, dienThoai, gioiTinh, quocTich));
            if (row > 0) {
                JOptionPane.showMessageDialog(rootPane, "Thêm thành công", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                resetText();
                cb.doAddKH();
                dispose();
            } else {
                JOptionPane.showMessageDialog(rootPane, "Thêm thất bại", "Thông báo", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnThemMoiActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHuyBo;
    private javax.swing.JButton btnLamMoi;
    private javax.swing.JButton btnThemMoi;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioNam;
    private javax.swing.JRadioButton jRadioNu;
    private javax.swing.JLabel jlbCMND;
    private javax.swing.JLabel jlbDiaChi;
    private javax.swing.JLabel jlbGioiTinh;
    private javax.swing.JLabel jlbMaKh;
    private javax.swing.JLabel jlbQuocTich;
    private javax.swing.JLabel jlbSDT;
    private javax.swing.JLabel jlbTenKh;
    private javax.swing.JLabel jlbTitle;
    private javax.swing.JTextField txtCMND;
    private javax.swing.JTextField txtDiaChi;
    private javax.swing.JTextField txtDienThoai;
    private javax.swing.JLabel txtErrorCMND;
    private javax.swing.JLabel txtErrorDiaChi;
    private javax.swing.JLabel txtErrorDienThoai;
    private javax.swing.JLabel txtErrorMaKH;
    private javax.swing.JLabel txtErrorQuocTich;
    private javax.swing.JLabel txtErrorTenKH;
    private javax.swing.JTextField txtMaKH;
    private javax.swing.JTextField txtQuocTich;
    private javax.swing.JTextField txtTenKH;
    // End of variables declaration//GEN-END:variables
}
