/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.qlks.view.internalframe.action;

import com.qlks.dao.impl.LoaiPhongDAO;
import com.qlks.dao.impl.LoaiTinhTrangDAO;
import com.qlks.dao.impl.PhongDAO;
import com.qlks.models.LoaiPhong;
import com.qlks.models.LoaiTinhTrang;
import com.qlks.models.Phong;
import java.util.List;
import java.util.ResourceBundle;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author hello
 */
public class AddPhong extends javax.swing.JInternalFrame {

    private PhongDAO phongDAO;
    private LoaiPhongDAO loaiPhongDAO;
    private List<LoaiPhong> lstLoaiPhong;
    private DefaultComboBoxModel modelLoaiPhong;
    private LoaiTinhTrangDAO loaiTinhTrangDAO;
    private List<LoaiTinhTrang> lstLoaiTinhTrang;
    private DefaultComboBoxModel modelLoaiTinhTrang;

    CallBackAdd cb;
    private ResourceBundle rb;

    public interface CallBackAdd {

        void doAdd();
    }

    /**
     * Creates new form AddKhachHang
     */
    public AddPhong(CallBackAdd _cb, ResourceBundle rb) {
        initComponents();
        phongDAO = new PhongDAO();

        modelLoaiPhong = new DefaultComboBoxModel();
        loaiPhongDAO = new LoaiPhongDAO();
        lstLoaiPhong = loaiPhongDAO.getAll();

        modelLoaiTinhTrang = new DefaultComboBoxModel();
        loaiTinhTrangDAO = new LoaiTinhTrangDAO();
        lstLoaiTinhTrang = loaiTinhTrangDAO.getAll();

        resetText();
        this.cb = _cb;
        initDataLoaiPhong();
        initDataLoaiTinhTrang();
        this.rb = rb;
        translate(this.rb);
    }

    public void initDataLoaiPhong() {
        for (LoaiPhong adv : lstLoaiPhong) {
            modelLoaiPhong.addElement(adv);
            System.out.println("Loại phòng - " + adv.getMaLoaiPhong());
        }
        jcbMaLoaiPhong.setModel(modelLoaiPhong);
    }

    public void initDataLoaiTinhTrang() {
        for (LoaiTinhTrang adv : lstLoaiTinhTrang) {
            modelLoaiTinhTrang.addElement(adv);
        }
        jComboBoxMaTinhTrang.setModel(modelLoaiTinhTrang);
    }

    public void resetText() {
        txtErrorMaPhong.setText("");
        txtMaPhong.setText("");
        txtGhiChu.setText("");
    }

    public void translate(ResourceBundle rb) {
        this.rb = rb;
        setTitle(this.rb.getString("AddPhong"));
        jlbTitle.setText(this.rb.getString("AddPhong"));
        jlbMaPhong.setText(this.rb.getString("JIFQuanLyPhongMaPhong"));
        JlbTenLoaiPhong.setText(this.rb.getString("AddLoaiPhongTen"));
        jlbGhiChu.setText(this.rb.getString("JIFQuanLyPhongGhiChu"));
        jlbTinhTrang.setText(this.rb.getString("JIFQuanLyPhongTinhTrang"));


        btnLamMoi.setText(this.rb.getString("BtnLamMoi"));
        btnHuyBo.setText(this.rb.getString("BtnHuy"));
        btnThemMoi.setText(this.rb.getString("BtnThemMoi"));

        revalidate();
        repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jlbTitle = new javax.swing.JLabel();
        jlbMaPhong = new javax.swing.JLabel();
        txtMaPhong = new javax.swing.JTextField();
        JlbTenLoaiPhong = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jlbGhiChu = new javax.swing.JLabel();
        btnHuyBo = new javax.swing.JButton();
        btnThemMoi = new javax.swing.JButton();
        btnLamMoi = new javax.swing.JButton();
        txtErrorMaPhong = new javax.swing.JLabel();
        jcbMaLoaiPhong = new javax.swing.JComboBox<>();
        jComboBoxMaTinhTrang = new javax.swing.JComboBox<>();
        jlbTinhTrang = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtGhiChu = new javax.swing.JTextArea();

        setClosable(true);
        setIconifiable(true);

        jlbTitle.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlbTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbTitle.setText("THÊM MỚI PHÒNG");

        jlbMaPhong.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jlbMaPhong.setText("Mã phòng:");

        JlbTenLoaiPhong.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        JlbTenLoaiPhong.setText("Tên loại phòng:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jlbGhiChu.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jlbGhiChu.setText("Ghi chú:");

        btnHuyBo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnHuyBo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/qlks/icon/icon_close.png"))); // NOI18N
        btnHuyBo.setText("Hủy bỏ");
        btnHuyBo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHuyBoActionPerformed(evt);
            }
        });

        btnThemMoi.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnThemMoi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/qlks/icon/icon_add.png"))); // NOI18N
        btnThemMoi.setText("Thêm mới");
        btnThemMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemMoiActionPerformed(evt);
            }
        });

        btnLamMoi.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnLamMoi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/qlks/icon/icon_refresh.png"))); // NOI18N
        btnLamMoi.setText("Làm mới");
        btnLamMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLamMoiActionPerformed(evt);
            }
        });

        txtErrorMaPhong.setForeground(new java.awt.Color(255, 51, 51));
        txtErrorMaPhong.setText("...");

        jlbTinhTrang.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jlbTinhTrang.setText("Tình trạng:");

        txtGhiChu.setColumns(20);
        txtGhiChu.setRows(5);
        jScrollPane1.setViewportView(txtGhiChu);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlbMaPhong)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(JlbTenLoaiPhong, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jlbGhiChu, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(btnLamMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnHuyBo, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(25, 25, 25)
                                        .addComponent(btnThemMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jlbTinhTrang)
                                        .addGap(29, 29, 29)
                                        .addComponent(jComboBoxMaTinhTrang, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jcbMaLoaiPhong, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(65, 65, 65))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtErrorMaPhong, javax.swing.GroupLayout.DEFAULT_SIZE, 353, Short.MAX_VALUE)
                            .addComponent(txtMaPhong))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(241, Short.MAX_VALUE)
                .addComponent(jlbTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(232, 232, 232))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jlbTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbMaPhong)
                    .addComponent(txtMaPhong, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addComponent(txtErrorMaPhong)
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JlbTenLoaiPhong)
                    .addComponent(jcbMaLoaiPhong, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxMaTinhTrang, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlbTinhTrang))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(jlbGhiChu))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(51, 51, 51)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLamMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHuyBo, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnThemMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(51, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLamMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLamMoiActionPerformed
        resetText();
    }//GEN-LAST:event_btnLamMoiActionPerformed

    private void btnHuyBoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHuyBoActionPerformed
        resetText();
        dispose();
    }//GEN-LAST:event_btnHuyBoActionPerformed

    private void btnThemMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemMoiActionPerformed
        Boolean check = true;
        String maPhong = txtMaPhong.getText();

        LoaiPhong lp = (LoaiPhong) modelLoaiPhong.getSelectedItem();
        String maLoaiPhong = lp.getMaLoaiPhong();

        LoaiTinhTrang loaiTT = (LoaiTinhTrang) modelLoaiTinhTrang.getSelectedItem();
        int maLoaiTT = loaiTT.getMaLoaiTinhTrangPhong();
        String ghiChu = txtGhiChu.getText();

        if (maPhong.length() <= 0) {
            txtErrorMaPhong.setText("Mã không được để trống");
            check = false;
        } else if (maPhong.length() > 3) {
            txtErrorMaPhong.setText("Mã có tối đa là 3 ký tự");
            check = false;
        } else {
            txtErrorMaPhong.setText("");
        }

        try {
            List<Phong> lstCheckID = phongDAO.getByMaPhong(maPhong);
            if (lstCheckID.size() > 0) {
                txtErrorMaPhong.setText("Mã phòng đã tồn tại !");
                check = false;
            }
        } catch (Exception e) {
            txtErrorMaPhong.setText("Mã phòng đã tồn tại !");
            check = false;
        }

        if (check == true) {
            int row = phongDAO.add(new Phong(maPhong, maLoaiPhong, maLoaiTT, ghiChu));
            if (row > 0) {
                JOptionPane.showMessageDialog(rootPane, "Thêm thành công", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                resetText();
                cb.doAdd();
                dispose();
            } else {
                JOptionPane.showMessageDialog(rootPane, "Thêm thất bại", "Thông báo", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnThemMoiActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JlbTenLoaiPhong;
    private javax.swing.JButton btnHuyBo;
    private javax.swing.JButton btnLamMoi;
    private javax.swing.JButton btnThemMoi;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<LoaiTinhTrang> jComboBoxMaTinhTrang;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<LoaiPhong> jcbMaLoaiPhong;
    private javax.swing.JLabel jlbGhiChu;
    private javax.swing.JLabel jlbMaPhong;
    private javax.swing.JLabel jlbTinhTrang;
    private javax.swing.JLabel jlbTitle;
    private javax.swing.JLabel txtErrorMaPhong;
    private javax.swing.JTextArea txtGhiChu;
    private javax.swing.JTextField txtMaPhong;
    // End of variables declaration//GEN-END:variables
}
