/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.qlks.view.internalframe.action;

import java.util.ResourceBundle;

/**
 *
 * @author hello
 */
public class SearchKhachHang extends javax.swing.JInternalFrame {

    CallBackSearch cb;
    private ResourceBundle rb;

    public interface CallBackSearch {

        void doSearch(String maSearchInput, String tenSearchInput, String CMNDSearchInput,
                String diaChiSearchInput, String dienThoaiSearchInput, Boolean gioiTinhSearchInput, String quocTichSearchInput);
    }

    /**
     * Creates new form AddKhachHang
     */
    public SearchKhachHang(CallBackSearch _cb, ResourceBundle rb) {
        initComponents();
        resetText();
        this.cb = _cb;
        this.rb = rb;
        translate(this.rb);
    }

    public void resetText() {
        txtErrorCMND.setText("");
        txtErrorDiaChi.setText("");
        txtErrorDienThoai.setText("");
        txtErrorMaKH.setText("");
        txtErrorQuocTich.setText("");
        txtErrorTenKH.setText("");

        txtDiaChi.setText("");
        txtMaKH.setText("");
        txtQuocTich.setText("");
        txtTenKH.setText("");
        txtDienThoai.setText("");
        txtCMND.setText("");
    }

    public void translate(ResourceBundle rb) {
        this.rb = rb;
        setTitle(this.rb.getString("SearchKhachHang"));
        jlbTitle.setText(this.rb.getString("SearchKhachHang"));
        jlbMaKh.setText(this.rb.getString("JIFQLKhachHangMa"));
        jlbTenKh.setText(this.rb.getString("JIFQLKhachHangTen"));
        jlbCMND.setText(this.rb.getString("JIFQLKhachHangCMND"));
        jlbDiaChi.setText(this.rb.getString("JIFQLKhachHangDiaChi"));
        jlbSDT.setText(this.rb.getString("JIFQLKhachHangSDT"));
        jlbQuocTich.setText(this.rb.getString("JIFQLKhachHangQuocTich"));
        jlbGioiTinh.setText(this.rb.getString("JIFQLKhachHangGioiTinh"));
        jRadioNam.setText(this.rb.getString("AddNdNam"));
        jRadioNu.setText(this.rb.getString("AddNdNu"));

        btnLamMoi.setText(this.rb.getString("BtnLamMoi"));
        btnHuyBo.setText(this.rb.getString("BtnHuy"));
        btnTimKiem.setText(this.rb.getString("BtnTimKiem"));

        revalidate();
        repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupGioiTinh = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jlbTitle = new javax.swing.JLabel();
        jlbMaKh = new javax.swing.JLabel();
        txtMaKH = new javax.swing.JTextField();
        jlbTenKh = new javax.swing.JLabel();
        txtTenKH = new javax.swing.JTextField();
        jlbCMND = new javax.swing.JLabel();
        jlbDiaChi = new javax.swing.JLabel();
        txtDiaChi = new javax.swing.JTextField();
        txtQuocTich = new javax.swing.JTextField();
        jlbSDT = new javax.swing.JLabel();
        jlbGioiTinh = new javax.swing.JLabel();
        jlbQuocTich = new javax.swing.JLabel();
        jRadioNam = new javax.swing.JRadioButton();
        jRadioNu = new javax.swing.JRadioButton();
        btnHuyBo = new javax.swing.JButton();
        btnTimKiem = new javax.swing.JButton();
        btnLamMoi = new javax.swing.JButton();
        txtErrorMaKH = new javax.swing.JLabel();
        txtErrorTenKH = new javax.swing.JLabel();
        txtErrorCMND = new javax.swing.JLabel();
        txtErrorDiaChi = new javax.swing.JLabel();
        txtErrorDienThoai = new javax.swing.JLabel();
        txtErrorQuocTich = new javax.swing.JLabel();
        txtCMND = new javax.swing.JTextField();
        txtDienThoai = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);

        jlbTitle.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlbTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbTitle.setText("TÌM KIẾM KHÁCH HÀNG");

        jlbMaKh.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jlbMaKh.setText("Mã khách hàng:");

        jlbTenKh.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jlbTenKh.setText("Tên khách hàng:");

        txtTenKH.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jlbCMND.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jlbCMND.setText("CMND:");

        jlbDiaChi.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jlbDiaChi.setText("Địa chỉ:");

        txtDiaChi.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        txtQuocTich.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jlbSDT.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jlbSDT.setText("Điện thoại:");

        jlbGioiTinh.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jlbGioiTinh.setText("Giới tính:");

        jlbQuocTich.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jlbQuocTich.setText("Quốc tịch:");

        buttonGroupGioiTinh.add(jRadioNam);
        jRadioNam.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jRadioNam.setText("Nam");

        buttonGroupGioiTinh.add(jRadioNu);
        jRadioNu.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jRadioNu.setText("Nữ");

        btnHuyBo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnHuyBo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/qlks/icon/icon_close.png"))); // NOI18N
        btnHuyBo.setText("Hủy bỏ");
        btnHuyBo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHuyBoActionPerformed(evt);
            }
        });

        btnTimKiem.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnTimKiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/qlks/icon/icon_search.png"))); // NOI18N
        btnTimKiem.setText("Tìm kiếm");
        btnTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemActionPerformed(evt);
            }
        });

        btnLamMoi.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnLamMoi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/qlks/icon/icon_refresh.png"))); // NOI18N
        btnLamMoi.setText("Làm mới");
        btnLamMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLamMoiActionPerformed(evt);
            }
        });

        txtErrorMaKH.setForeground(new java.awt.Color(255, 51, 51));
        txtErrorMaKH.setText("...");

        txtErrorTenKH.setForeground(new java.awt.Color(255, 0, 0));
        txtErrorTenKH.setText("...");

        txtErrorCMND.setForeground(new java.awt.Color(255, 0, 0));
        txtErrorCMND.setText("...");

        txtErrorDiaChi.setForeground(new java.awt.Color(255, 51, 51));
        txtErrorDiaChi.setText("...");

        txtErrorDienThoai.setForeground(new java.awt.Color(255, 0, 0));
        txtErrorDienThoai.setText("...");

        txtErrorQuocTich.setForeground(new java.awt.Color(255, 0, 0));
        txtErrorQuocTich.setText("...");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(197, 197, 197)
                        .addComponent(jlbTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlbMaKh)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jlbSDT, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jlbCMND, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jlbGioiTinh, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 242, Short.MAX_VALUE)
                                .addComponent(btnLamMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnHuyBo, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(25, 25, 25)
                                .addComponent(btnTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jRadioNam)
                                        .addGap(18, 18, 18)
                                        .addComponent(jRadioNu))
                                    .addComponent(txtMaKH, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtErrorMaKH, javax.swing.GroupLayout.DEFAULT_SIZE, 211, Short.MAX_VALUE)
                                    .addComponent(txtErrorCMND, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtErrorDienThoai, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtCMND)
                                    .addComponent(txtDienThoai))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jlbDiaChi)
                                    .addComponent(jlbTenKh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jlbQuocTich, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtQuocTich)
                                    .addComponent(txtDiaChi, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtTenKH, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtErrorTenKH, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 313, Short.MAX_VALUE)
                                    .addComponent(txtErrorDiaChi, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtErrorQuocTich, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                .addGap(67, 67, 67))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jlbTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbMaKh)
                    .addComponent(txtMaKH, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlbTenKh)
                    .addComponent(txtTenKH, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtErrorMaKH)
                    .addComponent(txtErrorTenKH))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlbCMND)
                            .addComponent(jlbDiaChi)
                            .addComponent(txtDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(txtCMND)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtErrorCMND)
                    .addComponent(txtErrorDiaChi))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbSDT)
                    .addComponent(jlbQuocTich)
                    .addComponent(txtQuocTich, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDienThoai, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtErrorDienThoai)
                    .addComponent(txtErrorQuocTich))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbGioiTinh)
                    .addComponent(jRadioNam)
                    .addComponent(jRadioNu))
                .addGap(60, 60, 60)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLamMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHuyBo, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLamMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLamMoiActionPerformed
        buttonGroupGioiTinh.clearSelection();
        resetText();
    }//GEN-LAST:event_btnLamMoiActionPerformed

    private void btnHuyBoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHuyBoActionPerformed
        resetText();
        dispose();
    }//GEN-LAST:event_btnHuyBoActionPerformed

    private void btnTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemActionPerformed
        String maKH = txtMaKH.getText();
        String tenKH = txtTenKH.getText();
        String diaChi = txtDiaChi.getText();
        String quocTich = txtQuocTich.getText();
        String CMND = txtCMND.getText();
        String dienThoai = txtDienThoai.getText();
        Boolean gioiTinh = null;
        if (jRadioNu.isSelected()) {
            gioiTinh = false;
        } else if (jRadioNam.isSelected()) {
            gioiTinh = true;
        }
        cb.doSearch(maKH, tenKH, CMND, diaChi, dienThoai, gioiTinh, quocTich);
    }//GEN-LAST:event_btnTimKiemActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHuyBo;
    private javax.swing.JButton btnLamMoi;
    private javax.swing.JButton btnTimKiem;
    private javax.swing.ButtonGroup buttonGroupGioiTinh;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioNam;
    private javax.swing.JRadioButton jRadioNu;
    private javax.swing.JLabel jlbCMND;
    private javax.swing.JLabel jlbDiaChi;
    private javax.swing.JLabel jlbGioiTinh;
    private javax.swing.JLabel jlbMaKh;
    private javax.swing.JLabel jlbQuocTich;
    private javax.swing.JLabel jlbSDT;
    private javax.swing.JLabel jlbTenKh;
    private javax.swing.JLabel jlbTitle;
    private javax.swing.JTextField txtCMND;
    private javax.swing.JTextField txtDiaChi;
    private javax.swing.JTextField txtDienThoai;
    private javax.swing.JLabel txtErrorCMND;
    private javax.swing.JLabel txtErrorDiaChi;
    private javax.swing.JLabel txtErrorDienThoai;
    private javax.swing.JLabel txtErrorMaKH;
    private javax.swing.JLabel txtErrorQuocTich;
    private javax.swing.JLabel txtErrorTenKH;
    private javax.swing.JTextField txtMaKH;
    private javax.swing.JTextField txtQuocTich;
    private javax.swing.JTextField txtTenKH;
    // End of variables declaration//GEN-END:variables
}
