/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.qlks.view.internalframe.action;

import com.qlks.dao.impl.KhuyenMaiDAO;
import com.qlks.models.KhuyenMai;
import java.time.LocalDate;
import java.time.ZoneId;
import java.util.Date;
import java.util.ResourceBundle;
import javax.swing.JOptionPane;

/**
 *
 * @author hello
 */
public class UpdateKhuyenMai extends javax.swing.JInternalFrame {

    private KhuyenMaiDAO khuyenMaiDAO;
    private KhuyenMai quanlyKM;
    private int IdKM;
    CallBackUpdate cb;
    private ResourceBundle rb;

    public interface CallBackUpdate {

        void doUpdate();
    }

    /**
     * Creates new form AddKhachHang
     */
    public UpdateKhuyenMai(KhuyenMai khuyenMai, CallBackUpdate _cb,ResourceBundle rb) {
        initComponents();
        resetText();
        khuyenMaiDAO = new KhuyenMaiDAO();
        this.cb = _cb;
        IdKM = khuyenMai.getMaKhuyenMai();
        txtMaPhieu.setText(khuyenMai.getMaPhieu());
        txtGiaTri.setText(Float.toString(khuyenMai.getGiaTri()));
        txtNoiDung.setText(khuyenMai.getNoiDung());
        if (khuyenMai.isKieuTinh() == true) {
            jRadioPhanTram.setSelected(true);
        }
        if (khuyenMai.isTrangThai() == true) {
            jRadioDaSD.setSelected(true);
        }
        LocalDate ngayBDHM = khuyenMai.getNgayBatDau();
        LocalDate ngayKTKM = khuyenMai.getNgayKetThuc();

        Date dateBD = java.sql.Date.valueOf(ngayBDHM);
        Date dateKT = java.sql.Date.valueOf(ngayKTKM);
        jDateBatDau.setDate(dateBD);
        jDateKetThuc.setDate(dateKT);
                this.rb = rb;
        translate(this.rb);
    }

    public void resetText() {
        txtErrorDateBatDau.setText("");
        txtErrorDateKetThuc.setText("");
        txtErrorNoiDung.setText("");
        txtErrorMaPhieu.setText("");
        txtErrorGiaTri.setText("");

        txtMaPhieu.setText("");
        txtGiaTri.setText("");
        txtNoiDung.setText("");
    }
        public void translate(ResourceBundle rb) {
        this.rb = rb;
        setTitle(this.rb.getString("UpdateKhuyenMai"));
        jlbTitle.setText(this.rb.getString("UpdateKhuyenMai"));
        jlbMaPhieu.setText(this.rb.getString("JIFQLKhuyenMaiCode"));
        jlbGiaTri.setText(this.rb.getString("JIFQLKhuyenMaiGiaTri"));
        jlbNgayBatDau.setText(this.rb.getString("JIFQLKhuyenMaiNgayBatDau"));
        jlbNgayKetThuc.setText(this.rb.getString("JIFQLKhuyenMaiNgayKetThuc"));
        jlbNoiDung.setText(this.rb.getString("JIFQLKhuyenMaiNoiDung"));
        jlbTrangThai.setText(this.rb.getString("JIFQLKhuyenMaiTrangThai"));
        jlbKieuTinh.setText(this.rb.getString("JIFQLKhuyenMaiKieuTinh"));
        jRadioChuaSD.setText(this.rb.getString("JIFQLKhuyenMaiChuaSD"));
        jRadioDaSD.setText(this.rb.getString("JIFQLKhuyenMaiDaSuDung"));
        jRadioTrucTiep.setText(this.rb.getString("JIFQLKhuyenMaiTrucTiep"));
        jRadioPhanTram.setText(this.rb.getString("JIFQLKhuyenMaiPhanTram"));

        btnLamMoi.setText(this.rb.getString("BtnLamMoi"));
        btnHuyBo.setText(this.rb.getString("BtnHuy"));
        btnCapNhat.setText(this.rb.getString("BtnCapNhat"));

        revalidate();
        repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jlbTitle = new javax.swing.JLabel();
        jlbMaPhieu = new javax.swing.JLabel();
        txtMaPhieu = new javax.swing.JTextField();
        jlbGiaTri = new javax.swing.JLabel();
        txtGiaTri = new javax.swing.JTextField();
        jlbNgayBatDau = new javax.swing.JLabel();
        jlbNgayKetThuc = new javax.swing.JLabel();
        jlbNoiDung = new javax.swing.JLabel();
        jlbKieuTinh = new javax.swing.JLabel();
        jRadioTrucTiep = new javax.swing.JRadioButton();
        jRadioPhanTram = new javax.swing.JRadioButton();
        btnHuyBo = new javax.swing.JButton();
        btnCapNhat = new javax.swing.JButton();
        btnLamMoi = new javax.swing.JButton();
        txtErrorMaPhieu = new javax.swing.JLabel();
        txtErrorGiaTri = new javax.swing.JLabel();
        txtErrorDateBatDau = new javax.swing.JLabel();
        txtErrorDateKetThuc = new javax.swing.JLabel();
        txtErrorNoiDung = new javax.swing.JLabel();
        txtNoiDung = new javax.swing.JTextField();
        jlbTrangThai = new javax.swing.JLabel();
        jRadioDaSD = new javax.swing.JRadioButton();
        jRadioChuaSD = new javax.swing.JRadioButton();
        jDateKetThuc = new com.toedter.calendar.JDateChooser();
        jDateBatDau = new com.toedter.calendar.JDateChooser();

        setClosable(true);
        setIconifiable(true);
        setTitle("Cập nhật khuyến mại");

        jlbTitle.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlbTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbTitle.setText("CẬP NHẬT KHUYẾN MẠI");

        jlbMaPhieu.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jlbMaPhieu.setText("Mã phiếu:");

        txtMaPhieu.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jlbGiaTri.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jlbGiaTri.setText("Giá trị:");

        txtGiaTri.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jlbNgayBatDau.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jlbNgayBatDau.setText("Ngày bắt đầu:");

        jlbNgayKetThuc.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jlbNgayKetThuc.setText("Ngày kết thúc:");

        jlbNoiDung.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jlbNoiDung.setText("Nội dung:");

        jlbKieuTinh.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jlbKieuTinh.setText("Kiểu tính:");

        buttonGroup1.add(jRadioTrucTiep);
        jRadioTrucTiep.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jRadioTrucTiep.setSelected(true);
        jRadioTrucTiep.setText("Trực tiếp");

        buttonGroup1.add(jRadioPhanTram);
        jRadioPhanTram.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jRadioPhanTram.setText("Phần trăm");

        btnHuyBo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnHuyBo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/qlks/icon/icon_close.png"))); // NOI18N
        btnHuyBo.setText("Hủy bỏ");
        btnHuyBo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHuyBoActionPerformed(evt);
            }
        });

        btnCapNhat.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnCapNhat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/qlks/icon/icon_edit.png"))); // NOI18N
        btnCapNhat.setText("Cập nhật");
        btnCapNhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCapNhatActionPerformed(evt);
            }
        });

        btnLamMoi.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnLamMoi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/qlks/icon/icon_refresh.png"))); // NOI18N
        btnLamMoi.setText("Làm mới");
        btnLamMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLamMoiActionPerformed(evt);
            }
        });

        txtErrorMaPhieu.setForeground(new java.awt.Color(255, 51, 51));
        txtErrorMaPhieu.setText("...");

        txtErrorGiaTri.setForeground(new java.awt.Color(255, 0, 0));
        txtErrorGiaTri.setText("...");

        txtErrorDateBatDau.setForeground(new java.awt.Color(255, 0, 0));
        txtErrorDateBatDau.setText("...");

        txtErrorDateKetThuc.setForeground(new java.awt.Color(255, 51, 51));
        txtErrorDateKetThuc.setText("...");

        txtErrorNoiDung.setForeground(new java.awt.Color(255, 0, 0));
        txtErrorNoiDung.setText("...");

        txtNoiDung.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jlbTrangThai.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jlbTrangThai.setText("Trạng thái:");

        buttonGroup2.add(jRadioDaSD);
        jRadioDaSD.setText("Đã sử dụng");

        buttonGroup2.add(jRadioChuaSD);
        jRadioChuaSD.setSelected(true);
        jRadioChuaSD.setText("Chưa sử dụng");

        jDateKetThuc.setDateFormatString("dd/MM/yyyy");

        jDateBatDau.setDateFormatString("dd/MM/yyyy");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(197, 197, 197)
                        .addComponent(jlbTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlbMaPhieu)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jlbNoiDung, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jlbNgayBatDau, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jlbKieuTinh, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnLamMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnHuyBo, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(25, 25, 25)
                                .addComponent(btnCapNhat))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtNoiDung)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jRadioTrucTiep)
                                        .addGap(18, 18, 18)
                                        .addComponent(jRadioPhanTram))
                                    .addComponent(txtMaPhieu)
                                    .addComponent(jDateBatDau, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
                                    .addComponent(txtErrorDateBatDau, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtErrorMaPhieu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtErrorNoiDung, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jlbGiaTri)
                                    .addComponent(jlbTrangThai)
                                    .addComponent(jlbNgayKetThuc))
                                .addGap(23, 23, 23)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jRadioChuaSD)
                                        .addGap(28, 28, 28)
                                        .addComponent(jRadioDaSD))
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jDateKetThuc, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 283, Short.MAX_VALUE)
                                        .addComponent(txtErrorGiaTri, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtGiaTri, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(txtErrorDateKetThuc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))))
                .addGap(67, 67, 67))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jlbTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbMaPhieu)
                    .addComponent(txtMaPhieu, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlbGiaTri)
                    .addComponent(txtGiaTri, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtErrorMaPhieu)
                    .addComponent(txtErrorGiaTri))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(31, 31, 31)
                            .addComponent(jlbNgayBatDau)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                            .addComponent(jDateKetThuc, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtErrorDateKetThuc)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jDateBatDau, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlbNgayKetThuc))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtErrorDateBatDau)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbNoiDung)
                    .addComponent(txtNoiDung, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlbTrangThai)
                    .addComponent(jRadioChuaSD)
                    .addComponent(jRadioDaSD))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtErrorNoiDung)
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbKieuTinh)
                    .addComponent(jRadioTrucTiep)
                    .addComponent(jRadioPhanTram))
                .addGap(60, 60, 60)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLamMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHuyBo, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCapNhat))
                .addGap(56, 56, 56))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLamMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLamMoiActionPerformed
        jDateBatDau.setCalendar(null);
        jDateKetThuc.setCalendar(null);
        resetText();
    }//GEN-LAST:event_btnLamMoiActionPerformed

    private void btnHuyBoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHuyBoActionPerformed
        resetText();
        dispose();
    }//GEN-LAST:event_btnHuyBoActionPerformed

    private void btnCapNhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCapNhatActionPerformed
        Boolean check = true;
        String maPhieu = txtMaPhieu.getText();
        String giaTri = txtGiaTri.getText();
        String noiDung = txtNoiDung.getText();

        if (maPhieu.length() <= 0) {
            txtErrorMaPhieu.setText("Mã phiếu không được để trống");
            check = false;
        } else if (maPhieu.length() > 50) {
            txtErrorMaPhieu.setText("Mã phiếu có tối đa là 50 ký tự");
            check = false;
        } else {
            txtErrorMaPhieu.setText("");
        }

        if (giaTri.length() <= 0) {
            txtErrorGiaTri.setText("Tên không được để trống");
            check = false;
        }
        Float giaTriX = null;
        try {
            giaTriX = Float.parseFloat(giaTri);
            if (giaTriX < 0) {
                txtErrorGiaTri.setText("Giá trị tính phải lớn hơn hoặc bằng 0");
                check = false;
            }
        } catch (Exception e) {
            txtErrorGiaTri.setText("Giá trị tính phải lớn hơn hoặc bằng 0");
            check = false;
        }

        if (noiDung.length() <= 0) {
            txtErrorNoiDung.setText("Điện thoại không được để trống");
            check = false;
        } else if (noiDung.length() > 100) {
            txtErrorNoiDung.setText("Điện thoại có tối đa là 100 ký tự");
            check = false;
        } else {
            txtErrorNoiDung.setText("");
        }

        LocalDate dateBatDau = null;
        if (jDateBatDau.getDate() != null) {
            dateBatDau = jDateBatDau.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
        } else {
            txtErrorDateBatDau.setText("Ngày bắt đầu ko được để trống");
            check = false;
        }

        LocalDate dateKetThuc = null;
        if (jDateKetThuc.getDate() != null) {
            dateKetThuc = jDateKetThuc.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
        } else {
            txtErrorDateKetThuc.setText("Ngày kết thúc ko được để trống");
            check = false;
        }

        Boolean kieuTinh = false;
        if (jRadioPhanTram.isSelected()) {
            kieuTinh = true;
        }
        Boolean trangThai = false;
        if (jRadioDaSD.isSelected()) {
            trangThai = true;
        }
        if (check == true) {
            int row = khuyenMaiDAO.update(new KhuyenMai(IdKM, maPhieu, giaTriX, noiDung, dateBatDau, dateKetThuc, kieuTinh, trangThai));
            if (row > 0) {
                JOptionPane.showMessageDialog(rootPane, "Cập nhật thành công", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                resetText();
                cb.doUpdate();
                dispose();
            } else {
                JOptionPane.showMessageDialog(rootPane, "Cập nhật thất bại", "Thông báo", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnCapNhatActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCapNhat;
    private javax.swing.JButton btnHuyBo;
    private javax.swing.JButton btnLamMoi;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private com.toedter.calendar.JDateChooser jDateBatDau;
    private com.toedter.calendar.JDateChooser jDateKetThuc;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioChuaSD;
    private javax.swing.JRadioButton jRadioDaSD;
    private javax.swing.JRadioButton jRadioPhanTram;
    private javax.swing.JRadioButton jRadioTrucTiep;
    private javax.swing.JLabel jlbGiaTri;
    private javax.swing.JLabel jlbKieuTinh;
    private javax.swing.JLabel jlbMaPhieu;
    private javax.swing.JLabel jlbNgayBatDau;
    private javax.swing.JLabel jlbNgayKetThuc;
    private javax.swing.JLabel jlbNoiDung;
    private javax.swing.JLabel jlbTitle;
    private javax.swing.JLabel jlbTrangThai;
    private javax.swing.JLabel txtErrorDateBatDau;
    private javax.swing.JLabel txtErrorDateKetThuc;
    private javax.swing.JLabel txtErrorGiaTri;
    private javax.swing.JLabel txtErrorMaPhieu;
    private javax.swing.JLabel txtErrorNoiDung;
    private javax.swing.JTextField txtGiaTri;
    private javax.swing.JTextField txtMaPhieu;
    private javax.swing.JTextField txtNoiDung;
    // End of variables declaration//GEN-END:variables
}
